import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import { copyFileSync, writeFileSync } from 'fs'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  platform: 'node',
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'out/main.js',
})

if (prod) {
  await context.rebuild()
  copyFileSync('src/styles.css', 'out/styles.css')
  copyFileSync('manifest.json', 'out/manifest.json')
  copyFileSync('versions.json', 'out/versions.json')
  copyFileSync('LICENSE.txt', 'out/LICENSE.txt')
  copyFileSync('README.md', 'out/README.md')
  process.exit(0)
} else {
  await context.watch()
  copyFileSync('src/styles.css', 'out/styles.css')
  copyFileSync('manifest.json', 'out/manifest.json')
  writeFileSync('out/.hotreload', 'hot-reload')
}
